/**
 * Ranked top attractions by ISO 3166-1 alpha-2 country code.
 * Used for the "Explore more" / regional highlights section.
 */
export const TOP_ATTRACTIONS_BY_COUNTRY = {
  GH: {
    countryName: "Ghana",
    attractions: [
      "Cape Coast Castle",
      "Kakum National Park",
      "Mole National Park",
      "Kwame Nkrumah Mausoleum",
      "Labadi Beach",
      "Wli Waterfalls",
      "Elmina Castle",
      "Nzulezu Stilt Village",
      "Lake Volta",
      "Ada Foah",
      "Shai Hills Resource Reserve",
      "Boti Falls & Umbrella Rock",
      "Aburi Botanical Gardens",
      "Larabanga Mosque",
      "Manhyia Palace Museum",
      "Makola Market, Accra",
      "Osu Castle (Christiansborg)",
      "Busua Beach",
      "Tafi Atome Monkey Sanctuary",
      "Jamestown Lighthouse, Accra",
    ],
  },
  US: {
    countryName: "United States",
    attractions: [
      "Grand Canyon",
      "Universal Studios Hollywood",
      "Yosemite National Park",
      "Statue of Liberty",
      "Upper Antelope Canyon",
      "Summit One Vanderbilt",
      "Alcatraz Island",
      "Niagara Falls USA",
      "Disneyland Resort California",
      "Golden Gate Bridge",
      "Las Vegas Strip",
      "Kualoa Ranch",
      "The Metropolitan Museum of Art",
      "Empire State Building",
      "Diamond Head",
      "Hollywood",
      "Griffith Observatory",
      "Edge NYC",
      "Top of the Rock Observation Deck",
      "Disney California Adventure Park",
    ],
  },
  GB: {
    countryName: "United Kingdom",
    attractions: [
      "Tower of London",
      "British Museum",
      "Stonehenge",
      "Edinburgh Castle",
      "Buckingham Palace",
      "Westminster Abbey",
      "Roman Baths & Bath City",
      "Lake District National Park",
      "Giant's Causeway",
      "Windsor Castle",
      "York Minster",
      "Snowdonia National Park",
      "Stratford-upon-Avon",
      "The Roman City of Chester",
      "The Scottish Highlands",
      "Cambridge University Colleges",
      "Oxford University & Bodleian",
      "The Jurassic Coast",
      "St Paul's Cathedral",
      "The National Gallery London",
    ],
  },
  NG: {
    countryName: "Nigeria",
    attractions: [
      "Zuma Rock",
      "Yankari Game Reserve",
      "Olumo Rock",
      "Obudu Mountain Resort",
      "Lekki Conservation Centre",
      "Nike Art Gallery, Lagos",
      "Idanre Hills",
      "Kajuru Castle",
      "Erin Ijesha Waterfalls",
      "Tinapa Business Resort",
      "Coconut Beach, Badagry",
      "Osun-Osogbo Sacred Grove",
      "Ancient Kano City Walls",
      "Gurara Falls",
      "Millennium Park Abuja",
      "Tarkwa Bay Beach",
      "Okomu National Park",
      "Ogbunike Caves",
      "Agodi Gardens Ibadan",
      "National Theatre Lagos",
    ],
  },
  KE: {
    countryName: "Kenya",
    attractions: [
      "Maasai Mara National Reserve",
      "Amboseli National Park",
      "Lake Nakuru National Park",
      "Tsavo East National Park",
      "Diani Beach",
      "Nairobi National Park",
      "Mount Kenya National Park",
      "Lamu Old Town",
      "Hell's Gate National Park",
      "Samburu National Reserve",
      "Lake Naivasha",
      "Fort Jesus Mombasa",
      "Giraffe Centre Nairobi",
      "David Sheldrick Elephant Orphanage",
      "Aberdare National Park",
      "Lake Victoria Kisumu",
      "Chyulu Hills",
      "Ol Pejeta Conservancy",
      "Kisite-Mpunguti Marine Park",
      "Karura Forest Reserve",
    ],
  },
  ZA: {
    countryName: "South Africa",
    attractions: [
      "Table Mountain",
      "Kruger National Park",
      "Cape of Good Hope",
      "Boulders Beach Penguins",
      "Robben Island",
      "Victoria & Alfred Waterfront",
      "The Cradle of Humankind",
      "Drakensberg Mountains",
      "Garden Route",
      "Soweto & Vilakazi Street",
      "Augrabies Falls",
      "Blyde River Canyon",
      "Hermanus Whale Watching",
      "Stellenbosch Winelands",
      "Addo Elephant National Park",
      "Sabi Sand Game Reserve",
      "Moses Mabhida Stadium SkyCar",
      "Kgalagadi Transfrontier Park",
      "Golden Gate Highlands Park",
      "Wild Coast Sun Trail",
    ],
  },
  FR: {
    countryName: "France",
    attractions: [
      "Eiffel Tower",
      "Palace of Versailles",
      "Louvre Museum",
      "Mont Saint-Michel",
      "Côte d'Azur Nice",
      "Château de Chambord",
      "Arc de Triomphe",
      "Notre-Dame de Paris",
      "Provence Lavender Routes",
      "Dune du Pilat",
      "Pont du Gard",
      "Chamonix & Mont Blanc",
      "Carcassonne Citadel",
      "Loire Valley Châteaux",
      "Sainte-Chapelle",
      "The Normandy D-Day Beaches",
      "French Riviera Cannes",
      "Basilique Notre-Dame de Fourvière Lyon",
      "Calanques near Marseille",
      "Île de Ré",
    ],
  },
  DE: {
    countryName: "Germany",
    attractions: [
      "Brandenburg Gate Berlin",
      "Neuschwanstein Castle",
      "Cologne Cathedral",
      "Black Forest Highlands",
      "Heidelberg Castle",
      "Sanssouci Palace Potsdam",
      "Romantic Road Medieval Towns",
      "Miniatur Wunderland Hamburg",
      "Zugspitze & Garmisch",
      "Reichstag Dome",
      "Rothenburg ob der Tauber",
      "Dresden Zwinger & Frauenkirche",
      "The Rhine Gorge",
      "Nuremberg Imperial Castle",
      "Museum Island Berlin",
      "Sylt Island",
      "Berchtesgaden Alps",
      "Augustusburg Palace Brühl",
      "Eagle's Nest",
      "Saxon Switzerland National Park",
    ],
  },
  ES: {
    countryName: "Spain",
    attractions: [
      "Sagrada Família Barcelona",
      "Alhambra of Granada",
      "Park Güell",
      "El Retiro Madrid",
      "Camino de Santiago",
      "Mezquita-Catedral de Córdoba",
      "Ibiza Old Town",
      "Teide National Park",
      "Royal Palace Madrid",
      "Plaza de España Seville",
      "Prado Museum",
      "Costa del Sol Marbella",
      "Ronda Bridge & Gorge",
      "Toledo Historic Centre",
      "Picos de Europa",
      "Casa Batlló Barcelona",
      "Guggenheim Bilbao",
      "Doñana National Park",
      "Mallorca Serra de Tramuntana",
      "Valencia City of Arts & Sciences",
    ],
  },
  NL: {
    countryName: "Netherlands",
    attractions: [
      "Rijksmuseum Amsterdam",
      "Keukenhof Gardens",
      "Van Gogh Museum",
      "Anne Frank House",
      "Kinderdijk Windmills",
      "Zaanse Schans",
      "Utrecht Old Canals",
      "Hoge Veluwe National Park",
      "Rotterdam Cube Houses",
      "Delft Historic Centre",
      "Madurodam The Hague",
      "Giethoorn Village",
      "Leiden Museums",
      "Efteling Theme Park",
      "Markthal Rotterdam",
      "Maastricht Vrijthof",
      "Delta Works Zeeland",
      "Haarlem Grote Markt",
      "Texel Island",
      "Bourtange Fortress",
    ],
  },
};

const FALLBACK = TOP_ATTRACTIONS_BY_COUNTRY.GH;

/**
 * @param {string | undefined} countryCode ISO 3166-1 alpha-2
 * @returns {{ countryName: string, attractions: string[] }}
 */
export function getAttractionsForCountry(countryCode) {
  const code = String(countryCode || "")
    .trim()
    .toUpperCase();
  if (code && TOP_ATTRACTIONS_BY_COUNTRY[code]) {
    return TOP_ATTRACTIONS_BY_COUNTRY[code];
  }
  return FALLBACK;
}

/** @param {string | undefined} countryCode */
export function hasAttractionPack(countryCode) {
  const code = String(countryCode || "")
    .trim()
    .toUpperCase();
  return Boolean(code && TOP_ATTRACTIONS_BY_COUNTRY[code]);
}
